### ISSUE TITLE
при създаване на фирма титуляр не се показва в списъка за смяна на оператор

### ISSUE THREAD

**Issue by naidenoff** [gozzoo/tansys#1]
Във футера остава старата фирма
както и на всички измервания, бележки и т.н

След рестартиране на програмата се показва ???

**Comment by naidenoff** [comment]
на футера остава старата фирма 
както и на всички измервания, бележки и т.н

**Comment by karky9** [comment]
test

**Comment by naidenoff** [comment]
При създадена нова фирма титуляр, когато се активира не се отразява веднага
След рестарт на програмата се появява и работи коректно
