### ISSUE TITLE
справка - някои стойности в таблицата минават на 2 реда

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#102]

**Comment by gozzoo** [comment]
авто справка - оправени са, продавач, купувач, склад и водач

**Comment by naidenoff** [comment]
колона склад при платформени е на два реда
![image](https://user-images.githubusercontent.com/36623314/39977234-32cf18fe-5741-11e8-9a54-435b570e9a56.png)

**Comment by naidenoff** [comment]
Виж също #103
