### ISSUE TITLE
поддръжка на външен дисплей

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#117]

**Comment by naidenoff** [comment]
Полетата са други лейбъли!!!

виж този екран

![image](https://user-images.githubusercontent.com/36623314/41508305-4ca4f1fc-724b-11e8-915e-9919c7622816.png)

**Comment by gozzoo** [comment]
@karky9 трябва да стане следното

- подзаглавията във формата (примерно Общо) да са бели с болд
- бутоните над всяка секция (примерно РЕДАКТИРАНЕ) да бъдат подравенени отдолу със подзаглавието
- вертикалните разстояния между полетата на формата да бъдат по малки
