### ISSUE TITLE
upgrade към angular 6.0

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#118]
променени са много неща и има голяма вероятност от бъгове

**Comment by naidenoff** [comment]
Разлика в разстоянията между полетата в платформени

![image](https://user-images.githubusercontent.com/36623314/40820307-771da78e-6568-11e8-93e1-1e8693e5afaa.png)

**Comment by naidenoff** [comment]
Старото 
![4761abeb8b668b31d8a8ad15128c19645dc5a9a082f4892e9c pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/36623314/40820349-a6242ff8-6568-11e8-82f5-44ffa2cd931b.png)

**Comment by naidenoff** [comment]
В НАСТРОЙКИ:

1. При добавяне на нова фирма, номенклатура и фирма титуляр
затваря формата на втори клик и Не добавя веднага ред с новия запис
След излизане от менюто и влизане наново - записа се появява!

2.   Не позволява запис на Нов потребител / свети поле "Потребител"
![image](https://user-images.githubusercontent.com/36623314/40820486-77b47258-6569-11e8-804b-e86c905b8947.png)
