### ISSUE TITLE
Печат на лазарен принтер проблем  с полета при бележката от платформени

### ISSUE THREAD

**Issue by naidenoff** [gozzoo/tansys#12]
![image](https://user-images.githubusercontent.com/36623314/36601212-453920ec-18bd-11e8-9d5a-06241d0a9785.png)

Виж полета долу дясно имат разминаване
Това се случва само при първото мерене и съответно печат

Ако после отвориш бележката от дневник платформени
тя се вижда и печати коректно

**Comment by gozzoo** [comment]
в момента е добре, остава отворено за да бъде тествано допълнително

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/39754976-af4dd33a-52cc-11e8-9930-fb388970fb74.png)

**Comment by gozzoo** [comment]
получава се при печат веднага след приключване. 

липсва дата

**Comment by naidenoff** [comment]
Това не е оправено!!!
подпис водач да стане само водач

**Comment by naidenoff** [comment]
става Подпис клиент
