### ISSUE TITLE
редактиране на платформено измерване

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#131]

**Comment by gozzoo** [comment]
@karky9 като отидеш на екран платфоремно измерване кликваш горе вляво над таблицата 'режим корекции'. в десния панел под полетата от формата и 2 бутона 'анаулиране' и 'редактиране'
едния да бъде максимално вдясно а другия максимално вляво.  да слязат доса надолу.

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/44050039-716b8ec2-9f3e-11e8-8233-4a2d886ae314.png)

**Comment by naidenoff** [comment]
има проблем не се дисплейва таблицата правя и мерене и нищо

това при старт на платформени 
![image](https://user-images.githubusercontent.com/36623314/44789875-6c052f00-aba6-11e8-8fa7-4a8733dac94a.png)

не се дисплейва таблицата
![image](https://user-images.githubusercontent.com/36623314/44789757-1b8dd180-aba6-11e8-9068-35038ea33bac.png)

после като рестартирам програмата 
това последно мерене се показва нормално
![image](https://user-images.githubusercontent.com/36623314/44789994-bdadb980-aba6-11e8-884a-9ee6abab5fa4.png)

при редактиране бутоните слизат надолу  долу дясно!!

![image](https://user-images.githubusercontent.com/36623314/44789984-b686ab80-aba6-11e8-97b4-a2978d8a6913.png)

**Comment by naidenoff** [comment]
Везна име прецаква екрана трябва да е в полето с данните от кантара в ляво
![image](https://user-images.githubusercontent.com/36623314/44866302-89f98f00-ac8d-11e8-93c4-4908fb58e6b7.png)

![image](https://user-images.githubusercontent.com/36623314/44866332-954cba80-ac8d-11e8-8626-71c98536d21b.png)

**Comment by naidenoff** [comment]
Забележка!!!
при приключване и печат бележката има забавяне преди да се визуализира !!!
