### ISSUE TITLE
редактиране на платформена бележка

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#133]

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/44542347-3af3ad00-a715-11e8-9dad-33c800a7f3a6.png)

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/44869486-625af480-ac96-11e8-88e7-d59aa7773dce.png)

**Comment by gozzoo** [comment]
![image](https://user-images.githubusercontent.com/296970/44953222-9c94e380-ae9a-11e8-87ca-bf0a83ee9944.png)
@karky9, трябва да са подравнени бутоните
