### ISSUE TITLE
дневник платформени измервания - бутон печат в бележката не е подравнен

### ISSUE THREAD

**Issue by naidenoff** [gozzoo/tansys#136]
Навсякъде в дневника лейбъл ПЕЧАТ да се подравни с  РЕДАКТИРАНЕ долу дясно

![image](https://user-images.githubusercontent.com/36623314/44952255-eaeab800-ae83-11e8-8aba-129d4a0a8b0b.png)

**Comment by gozzoo** [comment]
станало е при имплементацията на #133
