### ISSUE TITLE
редактиране на измерване - да може да се промени 'фирма титуляр'

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#147]

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51745613-12008b00-20ac-11e9-82b9-fd9bc75b8f0d.png)

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51749013-d8814d00-20b6-11e9-9940-17f37856b0b9.png)

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51749033-e505a580-20b6-11e9-8b91-2911d60f4191.png)

![image](https://user-images.githubusercontent.com/36623314/51749044-ec2cb380-20b6-11e9-9eac-7678f8c63f0e.png)

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51784749-8f80d580-2156-11e9-9141-9fb3afb661cf.png)

![image](https://user-images.githubusercontent.com/36623314/51784750-960f4d00-2156-11e9-800e-69c66a631873.png)

**Comment by naidenoff** [comment]
ок
