### ISSUE TITLE
всички форми - полетата с подсказка - елементите в списъка не съответстват на въведения текст

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#15]
евентуално решение на проблема: https://github.com/mapbox/node-sqlite3/issues/70

**Comment by gozzoo** [comment]
частично е оправено 
- за продукти работи напълно
- за фирми показва и излишни неща, но всички правилни също

**Comment by naidenoff** [comment]
За фирми тествах при авто и платформени
пиша буква Д
не ми излиза Дармакоп АД

А като на пиша буква А фирмата излиза най долу!!!
