### ISSUE TITLE
регистрация - комуникация със сървъра

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#152]
включва действия при всички състояния при регистрация:

- успешна регистрация
- няма връзка със сървъра
- продукта вече е регистриран
- променена конфигурация
- изтекъл лиценз

**Comment by gozzoo** [comment]
остава: 
-генериране на тестов лиценз
- екран 'faled' - размера на бутоните
- валидация на име на потребител - да се маркира полето

**Comment by naidenoff** [comment]
има интернет 
и пак се появява екрана че няма
при опитай отново няма реакция
при тест режим
иска логон - там не приема новосъздадения юсер

про проба с admin/bb
се появява този екран
![image](https://user-images.githubusercontent.com/36623314/51441401-c7f95d00-1cd9-11e9-816b-d6d5ab1d19c7.png)

**Comment by naidenoff** [comment]
ок
