### ISSUE TITLE
смяна на парола на текущия потребител

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#157]

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51382834-840f2800-1b20-11e9-8e46-c1a346fcba70.png)

**Comment by gozzoo** [comment]
мърдат полетата когато се появи съобщение за грешка

**Comment by naidenoff** [comment]
логиката работи и е ОК

**Comment by naidenoff** [comment]
ok
