### ISSUE TITLE
редактиране справка платформени - да се добави поле за филтриране за частно лице 

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#163]
полето се казва 'лице', съответно и името на колоната.

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51334303-38a93b00-1a88-11e9-895c-2ee34182a9e8.png)

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51334612-d8ff5f80-1a88-11e9-88e5-2bf48bf05f62.png)

**Comment by naidenoff** [comment]
ом

**Comment by naidenoff** [comment]
ок
