### ISSUE TITLE
редактиране справка авто - да е възможно филтриране по 'авто номер' и 'ремарке номер'

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#164]

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/51338606-ed485a00-1a92-11e9-951b-49bf5751f2d1.png)

**Comment by naidenoff** [comment]
Работят и двете 

Но липсва подсказка за НОМЕР РЕМЕРКЕ в панела 
за номера на камиона подсказката работи
