### ISSUE TITLE
форма авто измерване - при контролно измерване да може да се укаже дали измерването ще бъде еднократно

### ISSUE THREAD

**Issue by naidenoff** [gozzoo/tansys#171]
![image](https://user-images.githubusercontent.com/36623314/52007271-cd735600-24d6-11e9-85c2-7ec15297a2f2.png)

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/52007271-cd735600-24d6-11e9-85c2-7ec15297a2f2.png)

**Comment by gozzoo** [comment]
да се уточни:
- дали да пита за създаване на нова фирма при контролно измерване
- дали полето 'стока' да бъде задължително

**Comment by naidenoff** [comment]
ок

**Comment by naidenoff** [comment]
уточнени:

дали да пита за създаване на нова фирма при контролно измерване ДА
дали да има подсказка за име на фирма при контролно измерване - ако не пита за добавяне на фирма не трябва да има подсказки ДА
дали полето 'стока' да бъде задължително НЕ
дали продавач и купувач да бъдат задължителни НЕ

**Comment by gozzoo** [comment]
валидирането остава за #182
