### ISSUE TITLE
модул скрап - полета 'влажност' и 'примеси' да се вземат предвид при изчисяване на 'чисто тегло'

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#173]
- в system-settings да може да се укаже дали тези полета да се ползват
- полета 'влажност' и 'примеси' са в проценти
- да се изчислява 'чисто тегло' като от 'нето' се извади калкулиран отбив от тези полета
- полетата да се показват на бележката

**Comment by gozzoo** [comment]
да се уточни дали ще бъде полезно за другите клиенти

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/52294754-c5a62c80-2982-11e9-83eb-0cdf102c8085.png)
