### ISSUE TITLE
анулиране на платформено измерване от екран 'ново измерване'

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#28]
- да раобти като #23.
- да преичислява общата сума на бележката
- анулираните измервания да не се сумират на страница за нови платформени измервания

**Comment by gozzoo** [comment]
да раобти като #23.
да преичислява общата сума на бележката
да се уточни и добави задача 'анулиране на платформена бележка'

**Comment by naidenoff** [comment]
анулиране от екран 'ново измерване' ОК
