### ISSUE TITLE
измерване платформени везни - теглото може да бъде число със десетична запетая

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#30]
- дисплея да показва число със запетая
- при ръчно въвеждане на тегло да приема число със запетая
- отбив-а също да приема число със запетая
- в таблиците теглото да се показва със запетая (дневник и справки)

коментар Цецо: На малките везни под 1кг нищо не става и нямам десетична ,
Въвеждам 1.300 или 0.600 и нестава при ръчно
трябва да може да изписва 0,660    1,05   2,32 примерно

**Comment by naidenoff** [comment]
При ръчно въвеждане трябва да приема "запетайка" и "точка" от цифровата клавиатура
