### ISSUE TITLE
форма авто измерване - при невалиден рег. номер записва празен номер

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#33]
трябва да покаже полето като невалидно и да не позволи запис

при невалиден номер да се покаже съобщение (tooltip) че в полето мога да се въвеждат само цифри и латиница.

**Comment by naidenoff** [comment]
Липсва ПОДСКАЗКА която казва кои символи са разрешени!!!!

**Comment by gozzoo** [comment]
свързано с #39
