### ISSUE TITLE
настройки фирми - да има възможност за търсене

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#45]
@naidenoff трябва да се направи екран

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/39461416-197f4c4e-4d13-11e8-93d5-9416b8381abf.png)

![image](https://user-images.githubusercontent.com/36623314/39461425-23acd90c-4d13-11e8-8969-f31c47856ad0.png)

**Comment by gozzoo** [comment]
@karky9 малко слиза цялата таблица и се допира до пейджъра
