### ISSUE TITLE
платформени везни  - на бележките да се добави  данък ДОД 10%

### ISSUE THREAD

**Issue by naidenoff** [gozzoo/tansys#5]
На бележката става
====================
Обща сума:
Данък ДОД:     -10%
Сума за получаване:

**Comment by naidenoff** [comment]
На термо принтер тесен
"Сума за получаване:" излиза на два реда

![belezka 1-suma](https://user-images.githubusercontent.com/36623314/36484697-cb7ee2d2-1722-11e8-9e4f-37e76f547384.jpg)

**Comment by gozzoo** [comment]
Ще сменя името на полето на 'за получаване'
