### ISSUE TITLE
да се намали ширината на прозореца на приложението така че да се събира на монитор с резолюция 1280х800

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#74]
въпреки че ширината на прозореца на приложението е 1280 пиксела се оказва че Windows слага рамка с ширина 1 пиксел, така че за да се събере трябва да се намали ширината на приложението с 2 пиксела

**Comment by gozzoo** [comment]
да се тества на монитор с резолюция 1280х800

**Comment by naidenoff** [comment]
Тествано е на монитор с резолюция 1280х800
