### ISSUE TITLE
слагане на лого на фирма оператор

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#77]

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/39461399-f98513b0-4d12-11e8-90f3-f742d36ff092.png)

![image](https://user-images.githubusercontent.com/36623314/39461402-010eb6f4-4d13-11e8-91d1-40120f95f106.png)

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/39570333-ac0f4230-4ed0-11e8-89b0-edd3582d2730.png)

![image](https://user-images.githubusercontent.com/36623314/39570342-b28651e4-4ed0-11e8-9e66-f2ed54c09a08.png)

**Comment by naidenoff** [comment]
Да се добави текст под ЛОГО етикета

височина 70px

![image](https://user-images.githubusercontent.com/36623314/39632395-a3d8e718-4fbd-11e8-962a-4307f477254f.png)
