### ISSUE TITLE
таблиците в дневниците да имат един ред повече

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#79]
да се вдигне всичко нагоре, не е пролем че когато се отвори филтъра ще отиде на нивото на заглавието

**Comment by gozzoo** [comment]
трябва да се доуточнят и другите екрани

**Comment by naidenoff** [comment]
Трябва да се повдигнат редовете - сега опират в пейджъра
![image](https://user-images.githubusercontent.com/36623314/40095751-55995d54-58d6-11e8-880c-78f5ce2a10f6.png)
