### ISSUE TITLE
екран платформено измерване - таблицатга с иземрванията да има пейджър

### ISSUE THREAD

**Issue by gozzoo** [gozzoo/tansys#94]
сега расте неограничено и покрива бутоните долу

**Comment by gozzoo** [comment]
@naidenoff трябва да измислим как да се подредят нещата по екрана

**Comment by naidenoff** [comment]
![image](https://user-images.githubusercontent.com/36623314/39923773-bd4a4802-552d-11e8-8683-bb9a17a29818.png)

**Comment by gozzoo** [comment]
това е само врменно решение,  сега пейджъра е опасно близо до бутона за приключване. трябва да се измисли друго решение.

**Comment by gozzoo** [comment]
@naidenoff може да го погледнеш. не е завършено, има още работа по кода

**Comment by gozzoo** [comment]
@karky9 когато кликнеш върху ред и се покажат над таблицата бутоните АНУЛИРАЙ и РЕДАКТИРАЙ таблицата мърда малко

**Comment by naidenoff** [comment]
тест наци OK

**Comment by gozzoo** [comment]
да не се показва пейджър ако всички редове на таблицата се събират на една страница
